### ISSUE TITLE
Ausführungsfehler, mehr verstehe ich nicht :)

### ISSUE THREAD

**Issue by kgbvax** [FreiFunkMuenster/tools#5]
python neighbors.py  -d 2000 30:b5:c2:bc:f4:42 
Traceback (most recent call last):
  File "neighbors.py", line 293, in <module>
    info = map(get_info, nodes)
  File "neighbors.py", line 94, in get_info
    node_data = map_data['nodes'][node]['nodeinfo']
KeyError: None

**Comment by MPW1412** [comment]
Ich glaub 2 km ist als Radius zu groß. Mit 200m läuft es durch, aber da scheint was nicht mit der Berechnung zu stimmen. Man kann leider auf der Karte auch nicht mehr sehen, wer VPN hat und wer nicht :/

**Comment by MPW1412** [comment]
$ python neighbors.py -d 200 30:b5:c2:bc:f4:42 
2 Sprünge:
irrer-oktopus;00:19:99:5f:ae:2c;2a03:2260:115:0:219:99ff:fe5f:ae2c;2;;Ja
kgbvax-m2-f-nnw;68:72:51:24:e2:9e;2a03:2260:115:0:6a72:51ff:fe24:e29e;2;21.6621944336;Ja
kgbvax-batman-kompensator;c4:6e:1f:70:10:2a;2a03:2260:115:0:c66e:1fff:fe70:102a;2;;Ja
kgbvax-pius-cpe;30:b5:c2:bc:f4:42;2a03:2260:115:0:32b5:c2ff:febc:f442;2;0.0;Ja
1 Sprung:
kgbvax-m2-c;24:a4:3c:f0:b9:ae;2a03:2260:115:0:26a4:3cff:fef0:b9ae;1;19.4437514136;Ja
VPN:
Freifunk;30:b5:c2:c2:73:ba;2a03:2260:115:0:32b5:c2ff:fec2:73ba;0;;Ja


Hast du gar keinen VPN-Knoten mit Alfred?

**Comment by kgbvax** [comment]
Doch, irrer-oktopus.

**Comment by Fungur69** [comment]
Der KeyError bedeutet, dass irgendwo ein Knoten referenziert wird, der keine 'nodeinfo' in den Json-Daten hat. Muss mal schauen, wie ich das abfang.

**Comment by Fungur69** [comment]
Neue Version erzeugt, die den Fehler behebt für neighbors.py -d 2000 30:b5:c2:bc:f4:42

**Comment by kgbvax** [comment]
Astrein.

Gibt da noch Encoding Themen:

python neighbors.py -d 8000 30:b5:c2:bc:f4:42 | wc -l
Traceback (most recent call last):
  File "neighbors.py", line 321, in <module>
    print(line[1])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 15: ordinal not in range(128)

**Comment by Fungur69** [comment]
Noch ne neue Bugfix-Version. Der UnicodeEncodeError kommt nur, wenn die Ausgabe umgeleitet wird.
