### ISSUE TITLE
Wir brauchen ein Werkzeug um Knoten für Split zu selektieren

### ISSUE THREAD

**Issue by kgbvax** [FreiFunkMuenster/tools#6]
Ich stell das mal hier als Issue ein damit wir wissen wann wir es haben:

1.  Selektiere Knoten in einem Polygon (administrative Grenze - oder eine sinnvolle Annäherung) @descilla hatte da glaube ich auch was?

2.  Füge allen in 1. selektierten Knoten die per Mesh direkt oder indirekt verbundenen Knoten hinzu. Damit wir kein Mesh abschneiden oder Knoten verlieren die nicht auf der Karte stehen. 
Ergibt Menge B: Alle Knoten für neue Domain. \o/

3.  B' := aus der Menge B, wähle die Knoten die nur per Mesh und nicht per VPN verbunden sind  und "Blätter" sind.  Das sind die Knoten die bei einem Mesh / batman-adv Change sonst verloren gehen würden.

Update Strategie dann:
B'  aktualisieren
gefolgt von
B  aktualisieren

Danach: Validierung ob B auf neuer Version sind - dafür brauchen wir wohl auch ein Tool (und wenn's grep ist)

**Comment by MPW1412** [comment]
Wir haben beschlossen, dass wir die Knoten nicht im Hauruck Verfahren umziehen, sondern in kleinen Gruppen.

Und die ganzen restlichen Features erfüllt das Tool von Fungur69 exakt, die Syntax wird noch angepasst.

**Comment by kgbvax** [comment]
- Wer hat das wann und wo beschlossen? Ist an mir vorbeigegangen. 

- Nein, Mesh-Nodes-First erfüllt es gerade mal nicht.

**Comment by MPW1412** [comment]
Wurde schon vor Monaten mit Void so abgestimmt. Auch Lars aus der Möhnedomäne empfiehlt das, weil manche Knoten das Update erst in mehreren Anläufen annehmen. Wenn man nicht ~10% der Meshknoten verlieren will, muss man das mit Gefühl machen. 

Was genau erfüllt es nicht? Bei mir funktioniert es ganz normal:

$ python neighbors.py -d 200 68:72:51:04:f3:6e
2 Sprünge:
Aegidiistrasse-Sued;68:72:51:04:f3:6e;2a03:2260:115:0:6a72:51ff:fe04:f36e;2;0.0;Ja
1 Sprung:
Schuetzen;14:cc:20:6f:e2:18;2a03:2260:115:0:16cc:20ff:fe6f:e218;1;73.7773262192;Ja
Freifunk_CSt-2;e8:94:f6:2a:d4:58;2a03:2260:115:0:ea94:f6ff:fe2a:d458;1;6.30783404366;Ja
freifunk_gaer;30:b5:c2:22:e8:d6;2a03:2260:115:0:32b5:c2ff:fe22:e8d6;1;;Ja
VPN:
freifunk-kolpingsfamilie;e8:de:27:62:d6:da;2a03:2260:115:0:eade:27ff:fe62:d6da;0;288.041983152;Ja
marie-curie;e8:94:f6:69:b5:42;2a03:2260:115:0:ea94:f6ff:fe69:b542;0;54.244645903;Ja
dubtown_ms;e8:94:f6:29:f8:54;2a03:2260:115:0:ea94:f6ff:fe29:f854;0;104.089972262;Ja
Bella-Vita;e8:94:f6:4f:b2:7a;2a03:2260:115:0:ea94:f6ff:fe4f:b27a;0;46.521291797;Ja
freifunk_CSt-1;e8:94:f6:2a:d4:4e;2a03:2260:115:0:ea94:f6ff:fe2a:d44e;0;16.0730203324;Ja
edlabs-001;c0:4a:00:38:f0:54;2a03:2260:115:0:c24a:ff:fe38:f054;0;154.706912658;Ja
phonerepair.ms;e8:94:f6:6d:26:de;2a03:2260:115:0:ea94:f6ff:fe6d:26de;0;61.6680490054;Ja


Wenn du einen Anwendungsfall findest, wo es falsche Ergebnisse liefert, poste den, dann kann das bestimmt gefixt werden.

**Comment by kgbvax** [comment]
Ich wäre dir echt dankbar wenn due Texte mal ganz lesen würdest. Den hier nochmal einzugeben ist mir zu blöd.

**Comment by MPW1412** [comment]
Worauf spielst du an? Auf das Validierungstool? Das geht nicht automatisch, denn du weißt nicht, ob der Knoten vielleicht gerade updated, die Verbindung kurz verloren hat oder eventuell  das Update fehlgeschlagen ist und in wenigen Minuten wieder online ist.

Die einzige Validierungsmöglichkeit ist, dass er offline bleibt. Dazu kannst du das Skript nochmal ausführen, sind am nächsten Tag alle mit z.B. zwei Hops offline, kannst du die nächste Ebene ausrollen.

@Fungur69: Es wäre vielleicht praktisch die Zeitspanne, die die Knoten schon offline sind, noch mit auszugeben. Dann sieht man auf einen Blick, ob das Update überall durch ist.

**Comment by kgbvax** [comment]
Boah ey, vergiss es einfach.

**Comment by kgbvax** [comment]
Ich "spiele auf den dritten Absatz an".

**Comment by MPW1412** [comment]
Wie hättest du die Ausgabe denn gerne?

Die Knoten werden genau nach der Anzahl der Sprünge zum nächsten VPN-Uplink gruppiert:

2 Sprünge:
[...]
1 Sprung:
[...]
VPN:
[...]

Das tut genau das, was du oben unter drittens beschreibst.
