### ISSUE TITLE
neighbors.py: Weitere Robustheitsprobleme

### ISSUE THREAD

**Issue by kgbvax** [FreiFunkMuenster/tools#8]
python neighbors.py -d 20000000 30:b5:c2:bc:f4:42 | wc -l

Traceback (most recent call last):
  File "neighbors.py", line 296, in <module>
    info = map(get_info, nodes)
  File "neighbors.py", line 119, in get_info
    +('Ja' if map_data['nodes'][node]['flags']['online'] else 'Nein'))
KeyError: 'mac'
       0

**Comment by MPW1412** [comment]
Was zum Kuckuck veranstaltest du hier bitte gerade? 20.000 km ist ein vielfaches des Erddruchmessern. Warum willst du das Tool mit fuzzy Eingaben zum Absturz bringen?

**Comment by kgbvax** [comment]
Ich macht triviale Smoketest. 
Das ist dir scheinbar mal wieder Latte, du Pfuscher ;-)

Ein sehr großes d heisst ja nicht mehr als "alle Knoten".

Ich erwarte 
a) Das das Werkzeug in der Lage ist die Nodes korrekt zu parsen. Was es gerade nicht ist.  

b) Das Tool dann alle Nodes auswirft.

**Comment by Fungur69** [comment]
Hmm, ich bekomme dabei aber einen anderen Fehler wegen zu viel Rekursion. Ich schau mal, ob ich die Rekursion umgehen kann. Vorher seh ich den KeyError nicht.

**Comment by kgbvax** [comment]
Pull mal das habe ich gefixt.

**Comment by MPW1412** [comment]
Tests bringen nur etwas, wenn du ein klares Bestehen oder Nichtbestehen ablesen kannst. Alle Knoten kannst du aber „nicht Mal eben beim Überfliegen“ zuordnen.

Danke, dass du es trotzdem gefixt hast!

**Comment by kgbvax** [comment]
Ich kann die Knoten zählen und wenn da nur 400 rauskommen ist es offenbar falsch.

Komme mir vor wie bei Amateuren hier, sorry.

**Comment by MPW1412** [comment]
$ python neighbors.py -d 900000 -n 68:72:51:04:f3:6e|grep -i ':'|wc -l
1129

Mit deinem Fix hier erfasst er jetzt 1129 Knoten, es fehlen also 146.

**Comment by Fungur69** [comment]
Wenn mann die Distanz noch vergrößert, kommen Knoten rein, die keine IP-Adressen haben. Das hab ich jetzt in neuer Version abgefangen.
> python neighbors.py -d 900000000 -n 68:72:51:04:f3:6e|grep -i ':'|wc -l
1277

**Comment by kgbvax** [comment]
Das Distanz und IP Adresse irgendwie was miteinander zu tun haben klingt auch strange, oder?

**Comment by Fungur69** [comment]
Die folgenden Knoten sind ohne IP und kommen nur durch sehr große -d mit in die Liste:
ffms-monitoring
gateway-commander1024
gateway-fanlin
ffms-services
gateway-fusselkater
gateway-parad0x
gateway-sense

**Comment by kgbvax** [comment]
Ah, GWs. Das ist in Ordnung.
